### ISSUE TITLE
Plot labels in plot_aagi() not appearing

### ISSUE THREAD

**Issue by RussellAndrewEdson** [AAGI-Org-AU-Public/AAGIThemes#12]
Hi Adam and all,

I was looking into incorporating the `plot_aagi()` function in the short report template from `AAGITemplates`, and it seems like the plot axis labels are not being plotted? (testing with `plot_aagi(pressure)`, and `plot_aagi(pressure, xlab="x", ylab="y")`):
![image](https://github.com/user-attachments/assets/f921c422-b7ad-45c4-a345-23652e8a6864)

Checking the code, it looks like lines 84-89 of `plot_aagi.R` might be the culprit. They're emptying the labels if the labels are provided as arguments, which seems like the opposite of what you'd want. There also doesn't seem to be any code that grabs the axis labels from the dataset if they aren't provided (e.g., as in `plot_aagi(pressure)`):
![image](https://github.com/user-attachments/assets/e958a116-83e5-4be8-8d4b-1b8db3d0dade)

**Comment by adamhsparks** [comment]
Good catch. Thanks for the feedback.

**Comment by adamhsparks** [comment]
Ok, you can add labels now, https://github.com/AAGI-Org-AU-Public/AAGIThemes/commit/6c1aa7b51aa9f255346d165c1711a1c8096612a4

I'm trying to wrap my head around how to achieve what `plot(pressure)` does with a custom `plot()` function, but at least for now we can pass labels along and they're respected.

**Comment by adamhsparks** [comment]
yeah, I'm going to try that next. :)

**Comment by adamhsparks** [comment]
Closer, https://github.com/AAGI-Org-AU-Public/AAGIThemes/commit/d0f549974de0158e9076e2c362bf87e648216458.

But `plot_aagi(OrchardSprays[c(4,1)])` doesn't label the axis properly nor does it produce box plots like `plot(OrchardSprays[c(4,1)])` does.

**Comment by RussellAndrewEdson** [comment]
I'm still getting strange labels for the simple `plot_aagi(pressure)` case:
![image](https://github.com/user-attachments/assets/bfd8de53-53dc-4291-9a99-09e2ae6d046b)

If `x` is the `pressure` data.frame, then `x[[1]]` is just an unnamed vector, which means that calling `names()` on that (as line 93 of d0f549974de0158e9076e2c362bf87e648216458 does) would probably just give NULL or Index, as it appears to.

Why not just use the xlab and ylab from `xy` (and move the label check to after line 108 where that object gets created? That seems to do what we want even in the `OrchardSprays[c(4,1)]` case:
![image](https://github.com/user-attachments/assets/674a12b2-5fd5-4fc9-81a4-b89a0175622a)

And then if you wanted the Box plots for when `x` is a factor/character you can just have a check for that somewhere, and make a call to `graphics::boxplot` instead of `graphics::points` for that case.

**Comment by adamhsparks** [comment]
I'm contemplating refactoring the way this is all done, _e.g._, {basetheme} here https://github.com/karoliskoncevicius/basetheme/blob/master/R/basetheme.R

**Comment by adamhsparks** [comment]
I'm glad someone is checking this. TBH, I'd not because I just rely on {ggplot2}. 😃

**Comment by adamhsparks** [comment]
@RussellAndrewEdson, I've taken a much more pared back approach. Can you see if this now works for you?

**Comment by RussellAndrewEdson** [comment]
Confirmed, looks good to me:
![image](https://github.com/user-attachments/assets/e59ecee0-c4f8-49d4-83a9-8a93d1bd8ade)

Cheers!

**Comment by adamhsparks** [comment]
Thanks, @RussellAndrewEdson

**Comment by RussellAndrewEdson** [comment]
Something happened. I pulled the latest commit and tried compiling a doc with the standard `plot_aagi(pressure)` bizo. It looks like we've lost the x axis label in the plot now:
![image](https://github.com/user-attachments/assets/0e7f1b22-d3e2-431c-a30d-29a65c6c17c3)

**Comment by adamhsparks** [comment]
:sigh: OK.

**Comment by adamhsparks** [comment]
One more try! 😅

**Comment by adamhsparks** [comment]
Reference doc looks good...

https://aagi-org-au-public.github.io/AAGIThemes/reference/plot_aagi.html

**Comment by adamhsparks** [comment]
I'll stop fiddling with it now.
